apiVersion: apps.tanzu.vmware.com/v1
kind: ContainerApp
metadata:
  creationTimestamp: null
  name: spring-music-ga
spec:
  contact:
    team: warroyo
  build:
    nonSecretEnv:
    - name: BP_JVM_VERSION
      value: "17"
    buildpacks: {}
    path: ../..
  ports:
  - name: main
    port: 8080