name: TPK8S Gitops
run-name: ${{ github.actor }} deploying
on:
  push:
    branches:
      - "gitops-demo"
jobs:
  gitops-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tanzu CLI
        env:
          TANZU_CLI_VERSION: ${{vars.TANZU_CLI_VERSION}}
        run: |
          curl -Lo tanzu-cli-linux-amd64.tar.gz https://github.com/vmware-tanzu/tanzu-cli/releases/download/${TANZU_CLI_VERSION}/tanzu-cli-linux-amd64.tar.gz
          curl -Lo tanzu-cli-binaries-checksums.txt https://github.com/vmware-tanzu/tanzu-cli/releases/download/${TANZU_CLI_VERSION}/tanzu-cli-binaries-checksums.txt
          if [ "$(cat tanzu-cli-binaries-checksums.txt | grep tanzu-cli-linux-amd64.tar.gz)" != "$(sha256sum tanzu-cli-linux-amd64.tar.gz)" ]; then echo "Checksum does not match"; exit 1; fi
          tar -xf tanzu-cli-linux-amd64.tar.gz
          mv ${TANZU_CLI_VERSION}/tanzu-cli-linux_amd64 /usr/local/bin/tanzu
          tanzu ceip-participation set false
          tanzu config eula accept
          tanzu init
          tanzu version

      - name: Install tanzu plugins
        env:
          TANZU_CLI_INCLUDE_DEACTIVATED_PLUGINS_TEST_ONLY: 1
        run: |
          tanzu plugin install --group vmware-tanzu/app-developer

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}


      - name: Checkout gitops repo
        uses: actions/checkout@v4
        with:
          repository: warroyo/tpk8s-argo-gitops-demo
          path: gitops
          token: ${{ secrets.GH_PAT }}

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
            
      - name: Build the app and promote it to the dev space
        env:
          TANZU_API_TOKEN: ${{ secrets.API_TOKEN }}
          ENDPOINT: ${{ vars.API_ENDPOINT || 'console.cloud.vmware.com' }}
          TANZU_CLI_CLOUD_SERVICES_ORGANIZATION_ID: 77aee83b-308f-4c8e-b9c4-3f7a6f19ba75
        run: |
            tanzu login --endpoint ${ENDPOINT}
            # tanzu project use AMER-West
            # tanzu space use dev-sbx
            # tanzu build config --build-plan-source-type=ucp --containerapp-registry ghcr.io/{contact.team}/{name}
            # tanzu build -o ./deploy 
            # tanzu promote --from-build ./deploy --to ./gitops/amer-west/spaces/gitops-dev
      

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: "dev-${{env.GITHUB_RUN_ATTEMPT}}"
          commit_message: push application deployment to dev
          commit_user_name: warroyo
          create_branch: true
          repository: ./gitops

      - run: echo "🍏 This job's status is ${{ job.status }}."
